### ISSUE TITLE
Use Newer Version of Node - Currently Node 12

### ISSUE THREAD

**Issue by stephenandary** [emibcn/badge-action#26]
When Running in actions, a deprecation warning will occur because of version of node for this, and upload-artifact. Looking into if there is a newer version of upload artifact now for examples. If there is anything I can do for Badge-Action please let me know.

**Comment by emibcn** [comment]
Hi @stephenandary ,
Thanks for taking care of reporting it!
Could you share a link to the pipe run with the warning or a screenshot of it?

**Comment by emibcn** [comment]
By the way, this Action uses Node16:
https://github.com/emibcn/badge-action/blob/master/action.yml#L45

**Comment by stephenandary** [comment]
This is my output
```
[Generate Badge Image with Devcontainer Version Value](https://github.com/jamminmusic/Containers/actions/runs/3734902116/jobs/6338345874)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: emibcn/badge-action@v1.2.1

[Generate Badge Image with Devcontainer Version Value](https://github.com/jamminmusic/Containers/actions/runs/3734902116/jobs/6338345874#step:4:66)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
There is both a node error, and a set-output error based on how Github changed their handling of outputs to use $GITHUB_OUTPUT instead

I will take a look at that action, thank you for sharing it

**Comment by emibcn** [comment]
Hmmm, I see:
![image](https://user-images.githubusercontent.com/693791/208846820-b483fdd4-0239-4814-b5e9-27d22dd0af97.png)

You are using the old version of the Action. Use the latest (2.0.2) to get rid of that message. Also, you could use Dependabot to your Workflow actions: it will generate PRs whenever there is an update. Take a look into mine:
https://github.com/emibcn/badge-action/blob/master/.github/dependabot.yml#L16

![image](https://user-images.githubusercontent.com/693791/208847350-95dd2c76-e619-4ff0-b23d-cb171d2fa1b1.png)

The red rectangle is to get update only in my GitHub Workflow (the previous onw is for my JS dependencies).

**Comment by stephenandary** [comment]
Oh no. I grabbed the version from an example, I should have checked. Thanks so much. And that dependabot workflow is so useful! Thank you.

**Comment by stephenandary** [comment]
> Oh no. I grabbed the version from an example, I should have checked. Thanks so much. And that dependabot workflow is so useful! Thank you. 

Something I plan to try for this exact situation is Gitbook code syncing. It automatically updates code in docs when it changes. Haven't gotten there yet. Maybe this weekend I will tinker.

**Comment by emibcn** [comment]
> Oh no. I grabbed the version from an example, I should have checked. Thanks so much. And that dependabot workflow is so useful! Thank you.

Could you share the link of the example? Probably I wrote it and could update it, too.

**Comment by emibcn** [comment]
Ok, just updated this action README. If there's another one, I'll appreciate the link.

**Comment by stephenandary** [comment]
Sure! These are from links on the top level readme at the bottom of the readme below <https://github.com/emibcn/badge-action/blob/master/README.md#commit-the-changes-to-dedicated-branch>
1. <https://github.com/emibcn/badge-action/blob/6af286f6b6e5dcabe6fd7085e852e5e6ac7713a0/.github/workflows/test.yml>
2. <https://github.com/emibcn/badge-action/blob/88b8f35d4c9fbd776e921f3eea831d4fdb8d4387/.github/workflows/test.yml>
3. <https://github.com/emibcn/pywisp/blob/master/.github/workflows/test.yml#L178>

**Comment by emibcn** [comment]
Hi @stephenandary ,
I've just updated the links. Thank you for your help!
