### ISSUE TITLE
Add a `v2` floating version tag

### ISSUE THREAD

**Issue by StummeJ** [emibcn/badge-action#34]
This is a really cool action, but having to manually update the minor version changes can be a pain. Could you create a `v2` tag that's a floating major version, much like your `v1` tag?

**Comment by emibcn** [comment]
Hi @StummeJ ,

> having to manually update the minor version changes can be a pain

You can use dependabot to automatically do it for you ;) You can take an example from [this same repo](https://github.com/emibcn/badge-action/blob/808173dd03e2f30c980d03ee49e181626088eee8/.github/dependabot.yml#L16C1-L20C24).

Besides that, I've created the v2 tag pointing to the latest commit.
